### ISSUE TITLE
No point in the custom `atom-css-comb/configs/.csscomb.json` being a dotfile.

### ISSUE THREAD

**Issue by danielbayley** [jchouse/csscomb-atom#15]
I don't see the reason for this; just makes it more difficult on OS X. Plus it's already in a `.atom` 'dotfile' folder by default (although I personally changed `ATOM_REPOS_HOME` to be in my `Application Support` folder where it belongs IMO).

A better approach might be to be able to specify any path in the `config.cson` and read that from there. Which also kind of brings me to #14.

**Comment by jchouse** [comment]
This behavior is recommended by the developer. Will not fix https://github.com/csscomb/csscomb.js#2-configure
