### ISSUE TITLE
Is "vendor-prefix-align": true functioning as expected?

### ISSUE THREAD

**Issue by BMOv2600** [jchouse/csscomb-atom#17]
My .csscomb.json file includes `"vendor-prefix-align": true,` and after running the comb, prefixes are unaligned. 

Is there a step I'm missing? 

These prefixes looked like so before and after comb:

![unaligned](http://i.imgur.com/xaUZCao.png)

**Comment by jchouse** [comment]
1) Add rule { "vendor-prefix-align": true } to .csscomb.json
2) In package options set path to your .csscomb.json
3) Be happy!
