### ISSUE TITLE
Add ability to include full path to `csscomb.json` in settings

### ISSUE THREAD

**Issue by najela** [jchouse/csscomb-atom#18]
Hello I have 1 .csscomb.json file which I use for all my projects. I'll like to be able to link to this file in the settings.

**Comment by jchouse** [comment]
OK. I will try to add the ability to add a single configuration file.

**Comment by rnyberg** [comment]
Also would love to have this possibility.

**Comment by medifle** [comment]
I'd like to put my .csscomb.json file in the HOME directory.

**Comment by jchouse** [comment]
Added in 2.1.0.
