### ISSUE TITLE
line ending convertion

### ISSUE THREAD

**Issue by chesminsky** [jchouse/csscomb-atom#19]
Hi.
is there an option not to convert line endings ?
before:
![before](https://cloud.githubusercontent.com/assets/11498406/10691600/f714c2d4-7992-11e5-9abe-061f37420a7f.png)
after:
![after](https://cloud.githubusercontent.com/assets/11498406/10691603/01e7b55e-7993-11e5-9b02-4ff11810a857.png)

**Comment by jchouse** [comment]
Hi! Is this windows? I think it's from main package bug: https://github.com/csscomb/csscomb.js/issues/367

**Comment by chesminsky** [comment]
yes, on windows. ok then, will wait for update. now i installed additional atom package to convert line endings back again on save.
