### ISSUE TITLE
Please check the validity of the block starting from line 

### ISSUE THREAD

**Issue by Mladen1kus** [jchouse/csscomb-atom#27]
Hi there,
Thanks for this awesome plugin :)

It seems there is an issue when using certain sass ampersand selectors. I tried using the following:

.parent {
  &#{&} { }
}

When i try to comb the css after typing that, i get an error code as following:
Please check the validity of the block starting from line #n

Best regards,
Mladen

**Comment by jchouse** [comment]
Old bug from core.
