### ISSUE TITLE
Support for Polymer Web Components (CSS inline in HTML files)

### ISSUE THREAD

**Issue by abdonrd** [jchouse/csscomb-atom#28]
For example, check the [ibm-toolbar.html](https://github.com/IBMResearch/ibm-toolbar/blob/master/ibm-toolbar.html) element.

**Comment by jchouse** [comment]
To comb the css within html is to identify those rules that you want to sort and then sort. Is this what you mean?

**Comment by abdonrd** [comment]
@jchouse more or less. Maybe find the `<style>` tags if the file are `.html` and comb this CSS.

**Comment by jchouse** [comment]
O ok, I missed it. Good idea.

**Comment by jchouse** [comment]
In html already sorting, but cssComb get exception when in rule we have constructions like `::content &gt; [bottom-item]`, see the [video](https://screencast.com/t/5Tj4diu70drI)
