### ISSUE TITLE
Sort unknown properties alphabeticaly possible properties

### ISSUE THREAD

**Issue by ramjamx** [jchouse/csscomb-atom#30]
Is there a full list of possible properties for every configurable feature?
I'd try the automatic configurator but i'm stuck with the alphabeticaly order and don't want to answer 24 steps to just fix one.

In my case even if i put the following feature:
```  "sort-order-fallback": "abc",   ```    

the resulting sort is cba instead abc

Thank you.

**Comment by jchouse** [comment]
Can this help? Or I not correctly understood? https://github.com/csscomb/csscomb.js/blob/dev/doc/options.md#sort-order-fallback

**Comment by Daidalos117** [comment]
Please give me simple answer, how can I sort all properties alphabetically?

**Comment by jchouse** [comment]
Create your own config with properties masks in the right order. http://csscomb.com/docs/configuration 
the sample: https://github.com/csscomb/csscomb.js/blob/dev/config/yandex.json#L7
