### ISSUE TITLE
Errors when saving an HTML file

### ISSUE THREAD

**Issue by ericandrewlewis** [jchouse/csscomb-atom#41]
When I save an HTML file, I see an error `Please select the text for combing`

<img width="925" alt="screen shot 2018-03-31 at 6 59 55 pm" src="https://user-images.githubusercontent.com/1087646/38168276-b9c493b4-3515-11e8-8e35-ef8001c28dbd.png">

I'm not sure why CSS comb is running in this file...or why it's displaying an error.

If I follow the message down the rabbit hole and select all and then save in the HTML file, I get a different error `Please check validity of the block starting from line #1 CSScomb Core version: 4.2.0`

<img width="976" alt="screen shot 2018-03-31 at 7 00 38 pm" src="https://user-images.githubusercontent.com/1087646/38168280-daadb196-3515-11e8-9156-a8455517f189.png">

Am I doing something wrong here?

Thanks for this package, it works awesome in css files!

**Comment by paulbrause** [comment]
Same problem here, is it possible to exclude *.html from "run on save"?

Tried to use a custom config with `"exclude": [ ... "*.html"]`, but this doesn't work.

Any suggestions?

**Comment by jchouse** [comment]
Fixed on 3.5.0
