### ISSUE TITLE
Atom 0.189 plugin stylesheets check

### ISSUE THREAD

**Issue by ikeagold** [jchouse/csscomb-atom#6]
Store package style sheets in the styles/ directory instead of stylesheets/ in the atom-css-comb package

Called 6 times

Package.getStylesheetsPath - C:\Users\Administrator\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:448:9
Package.getStylesheetPaths - C:\Users\Administrator\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:459:32

**Comment by jchouse** [comment]
Will the new version 0.6.5. Tired of fighting with Windows, as soon as I reach the Mac OS, the new version is released.
